name: Lint
on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: upgrade pip
      run: pip install --upgrade pip
    - name: install cpplint
      run: pip install cpplint==1.4.4
    - name: make lint
      run: make lint
